-- Local dev seed.
--
-- Intentionally empty: the Local Workspace and its Contributor are seeded by the
-- migration 20260907000000_local_workspace.sql (ADR-0020), so a fresh
-- `supabase db reset` already opens straight into a usable app. Run
-- `SEED_ENV=development npm run seed:e2e` for demo rubrics, runs, and schedules.
