/**
 * Ship the styled, locale-aware Supabase Auth email templates (#346, #247) to the
 * hosted prod project via a SCOPED Management API PATCH.
 * ─────────────────────────────────────────────────────────────────────────────
 * Supabase keeps auth email templates in two disconnected places: `config.toml`
 * (read only by the LOCAL/self-hosted stack) and the hosted project (Dashboard or
 * Management API). Nothing syncs local → hosted on its own, and `supabase config
 * push` is all-or-nothing: it would apply the ENTIRE `[auth]` block — including
 * `[auth.external.*]` OAuth provider state and `additional_redirect_urls` — and so
 * could silently disable Dashboard-configured prod OAuth or clobber the redirect
 * allow-list. This script instead PATCHes the documented Management API endpoint
 * `/v1/projects/{ref}/config/auth` with ONLY the `mailer_subjects_*` /
 * `mailer_templates_*_content` fields, touching no other auth config.
 *
 * `config.toml` stays the single source of truth: subjects are read from its
 * `[auth.email.template.*]` blocks, bodies from the committed `content_path` HTML
 * (generated by `npm run gen:auth-emails`). Run via `npm run push:auth-emails`
 * (the `deploy-auth-emails` workflow runs it on prod, with SUPABASE_ACCESS_TOKEN +
 * SUPABASE_PROJECT_ID_PROD in the env).
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readConfigSectionField } from "./lib/config-toml.mts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const CONFIG_PATH = join(repoRoot, "supabase", "config.toml");

// config.toml `[auth.email.template.<key>]` -> Management API field stem (identical).
const TEMPLATES = ["confirmation", "email_change", "recovery", "reauthentication"] as const;

/**
 * Read a single `field` out of the `[auth.email.template.<key>]` section of
 * config.toml. The values we read — `subject` and `content_path` — are plain
 * TOML basic strings with no escape sequences, so the captured text is verbatim.
 */
function readTemplateField(
  toml: string,
  key: string,
  field: "subject" | "content_path",
): string {
  return readConfigSectionField(toml, `[auth.email.template.${key}]`, field);
}

function buildPatchBody(): Record<string, string> {
  const toml = readFileSync(CONFIG_PATH, "utf8");
  const body: Record<string, string> = {};
  for (const key of TEMPLATES) {
    const subject = readTemplateField(toml, key, "subject");
    let contentPath = readTemplateField(toml, key, "content_path");
    if (contentPath.startsWith("./")) contentPath = contentPath.slice(2);
    body[`mailer_subjects_${key}`] = subject;
    body[`mailer_templates_${key}_content`] = readFileSync(
      join(repoRoot, contentPath),
      "utf8",
    );
  }
  return body;
}

async function main(): Promise<number> {
  const ref = process.env.SUPABASE_PROJECT_ID_PROD;
  const token = process.env.SUPABASE_ACCESS_TOKEN;
  if (!ref || !token) {
    console.error(
      "Set SUPABASE_PROJECT_ID_PROD and SUPABASE_ACCESS_TOKEN before running.",
    );
    return 1;
  }

  const body = buildPatchBody();
  const res = await fetch(
    `https://api.supabase.com/v1/projects/${ref}/config/auth`,
    {
      method: "PATCH",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    },
  );

  if (!res.ok) {
    console.error(`PATCH failed: HTTP ${res.status}\n${await res.text()}`);
    return 1;
  }
  console.log(`Updated ${TEMPLATES.length} auth email templates (HTTP ${res.status})`);
  return 0;
}

process.exit(await main());
