# fly.toml app configuration file generated for baseline-prod-qjozmq on 2026-07-07T15:08:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'baseline-prod-qjozmq'
primary_region = 'iad'

[build]

[deploy]
  strategy = 'immediate'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
